labeler:
  - name: T1
    color: 112233
  - name: team/ss
    color: 3CBF01
    paths: 
      - "*"
  - name: team/aa
    color: 5D9801
    paths:
      - "data/*"
  - name: team/bb
    color: A14C05
    paths:
      - "README.*"      
